"""init

Revision ID: 7fc8648c9bc3
Revises: 
Create Date: 2025-03-02 12:55:58.082010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc8648c9bc3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sell_price', sa.Float(), nullable=False),
    sa.Column('image_reference', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('server_configuration',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('min_login_credits', sa.Float(), nullable=False),
    sa.Column('max_login_credits', sa.Float(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('last_login_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.create_table('login_history',
    sa.Column('login_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_date', sa.DateTime(), nullable=False),
    sa.Column('credits_awarded', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('login_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('PURCHASE', 'SALE', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('user_items',
    sa.Column('user_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('acquisition_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_item_id'),
    sa.UniqueConstraint('user_id', 'item_id', name='uix_user_item')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_items')
    op.drop_table('transactions')
    op.drop_table('login_history')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_table('users')
    op.drop_table('server_configuration')
    op.drop_table('items')
    # ### end Alembic commands ###
